language: node_js
node_js:
  - "10"

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "commit by travis ci robot."
  - git push "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:${PAGE_BRANCH}
# E: Build LifeCycle

branches:
  only:
    - github-pages
