language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
# S: Build Lifecycle
install:
  - npm install
script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "commit by travis ci robot."
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:${PAGE_BRANCH}
# E: Build LifeCycle

branches:
  only:
    - github-pages
