<template>
<div class="container mx-auto">
    <h3 class="my-12 text-center text-4xl text-gray-600 font-mono">the website index <a href="https://laracasts.com/index" class="text-sm text-blue-500 hover:text-blue-700">data from laracast</a>   </h3>
    <div class="md:mx-16 md:px-16">
        <sticky v-for="(data, key) in list" :data="data" :key="key"></sticky>
    </div>
</div>
</template>
<script>
import Sticky from '../components/Sticky.vue';

export default {
    components: {
        Sticky,
    },

    data() {
        return {
            list: [
                {
                    index: 'a', 
                    items: [
                        {label: "cceptance testing", count: 5, href: "#"},
                        {label: "accordion", count: 2, href: "#"},
                        {label: "achievement", count: 5, href: "#"},
                        {label: "activity", count: 5, href: "#"},
                        {label: "activity feed", count: 2, href: "#"},
                        {label: "adapter", count: 2, href: "#"},
                        {label: "ajax", count: 14, href: "#"},
                        {label: "algolia", count: 11, href: "#"},
                        {label: "angular", count: 1, href: "#"},
                        {label: "animation", count: 3, href: "#"},
                        {label: "annotation", count: 2, href: "#"},
                        {label: "apache", count: 1, href: "#"},
                        {label: "api", count: 22, href: "#"},
                        {label: "app", count: 5, href: "#"},
                        {label: "app-development", count: 2, href: "#"},
                        {label: "architecture", count: 3, href: "#"},
                        {label: "array", count: 1, href: "#"},
                        {label: "artisan", count: 20, href: "#"},
                        {label: "async", count: 2, href: "#"},
                        {label: "authentication", count: 23, href: "#"},
                        {label: "authorization", count: 18, href: "#"},
                        {label: "autocomplete", count: 1, href: "#"},
                        {label: "autocompletion", count: 1, href: "#"},
                        {label: "autoload", count: 2, href: "#"},
                        {label: "ava", count: 3, href: "#"},
                        {label: "avatar", count: 1, href: "#"},
                    ]
                },
                {
                    index: 'b',
                    items: [
                        {label: "babel" , count: 1, href: "#"},
                        {label: "bash" , count: 1, href: "#"},
                        {label: "bdd" , count: 4, href: "#"},
                        {label: "beanstalkd" , count: 3, href: "#"},
                        {label: "behat" , count: 9, href: "#"},
                        {label: "billing" , count: 23, href: "#"},
                        {label: "blade" , count: 17, href: "#"},
                        {label: "bootstrap" , count: 1, href: "#"},
                        {label: "boris" , count: 1, href: "#"},
                        {label: "bower" , count: 3, href: "#"},
                        {label: "bowery" , count: 1, href: "#"},
                        {label: "brew" , count: 1, href: "#"},
                        {label: "broadcast" , count: 4, href: "#"},
                        {label: "broadcasting" , count: 1, href: "#"},
                        {label: "browserify" , count: 5, href: "#"},
                        {label: "browsersync" , count: 1, href: "#"},
                        {label: "bug" , count: 1, href: "#"},
                        {label: "bugsnag" , count: 1, href: "#"},
                        {label: "bulma" , count: 1, href: "#"},
                        {label: "bus" , count: 1, href: "#"},
                        {label: "button" , count: 1, href: "#"}
                    ]
                },
                {
                    index: "c",
                    items: [
                        {label: "cache" , count: 19, href: "#"},
                        {label: "carbon" , count: 2, href: "#"},
                        {label: "carousel" , count: 1, href: "#"},
                        {label: "cashier" , count: 1, href: "#"},
                        {label: "chart" , count: 1, href: "#"},
                        {label: "class" , count: 1, href: "#"},
                        {label: "clean code" , count: 2, href: "#"},
                        {label: "clockwork" , count: 1, href: "#"},
                        {label: "code editor" , count: 40, href: "#"},
                        {label: "codeception" , count: 10, href: "#"},
                        {label: "coffeescript" , count: 1, href: "#"},
                        {label: "collection" , count: 10, href: "#"},
                        {label: "command" , count: 24, href: "#"},
                        {label: "command bus" , count: 3, href: "#"},
                        {label: "comment" , count: 2, href: "#"},
                        {label: "community" , count: 1, href: "#"},
                        {label: "compile" , count: 2, href: "#"},
                        {label: "component" , count: 17, href: "#"},
                        {label: "composer" , count: 16, href: "#"},
                        {label: "configuration" , count: 1, href: "#"},
                        {label: "confirm" , count: 1, href: "#"},
                        {label: "console" , count: 5, href: "#"},
                        {label: "continuous integration" , count: 3, href: "#"},
                        {label: "contract" , count: 1, href: "#"},
                        {label: "controller" , count: 11, href: "#"},
                        {label: "cookie" , count: 1, href: "#"},
                        {label: "cors" , count: 1, href: "#"},
                        {label: "counter" , count: 1, href: "#"},
                        {label: "cron" , count: 3, href: "#"},
                        {label: "crud" , count: 2, href: "#"},
                        {label: "csrf" , count: 4, href: "#"},
                        {label: "css" , count: 45, href: "#"},
                        {label: "css3" , count: 1, href: "#"},
                        {label: "curl" , count: 2, href: "#"},
                        {label: "cloudflare", count: 1, href: "#"}
                    ],
                },
                {
                    index: "d",
                    items: [
                        {label: "daemon", count: 1, href: "#"},
                        {label: "database", count: 24, href: "#"},
                        {label: "date", count: 1, href: "#"},
                        {label: "ddd", count: 4, href: "#"},
                        {label: "debounce", count: 2, href: "#"},
                        {label: "debug", count: 5, href: "#"},
                        {label: "decorator", count: 6, href: "#"},
                        {label: "definition", count: 1, href: "#"},
                        {label: "dependency", count: 2, href: "#"},
                        {label: "dependency injection", count: 6, href: "#"},
                        {label: "deploy", count: 3, href: "#"},
                        {label: "design pattern", count: 29, href: "#"},
                        {label: "dialog", count: 1, href: "#"},
                        {label: "directive", count: 1, href: "#"},
                        {label: "directory", count: 1, href: "#"},
                        {label: "dispatcher", count: 1, href: "#"},
                        {label: "dns", count: 1, href: "#"},
                        {label: "dropdown", count: 2, href: "#"},
                        {label: "dusk", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'e',
                    items: [
                        {label: "echo", count: 9, href: "#"},
                        {label: "editor", count: 1, href: "#"},
                        {label: "elixir", count: 25, href: "#"},
                        {label: "eloquent", count: 64, href: "#"},
                        {label: "encapsulation", count: 1, href: "#"},
                        {label: "entity", count: 2, href: "#"},
                        {label: "environment", count: 2, href: "#"},
                        {label: "envoy", count: 1, href: "#"},
                        {label: "envoyer", count: 1, href: "#"},
                        {label: "event", count: 38, href: "#"},
                        {label: "exception", count: 6, href: "#"},
                        {label: "extension", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'f',
                    items: [
                        {label: "facade", count: 8, href: "#"},
                        {label: "factory", count: 7, href: "#"},
                        {label: "fake", count: 4, href: "#"},
                        {label: "faker", count: 5, href: "#"},
                        {label: "favorite", count: 1, href: "#"},
                        {label: "favoriting", count: 2, href: "#"},
                        {label: "feature", count: 1, href: "#"},
                        {label: "feed", count: 7, href: "#"},
                        {label: "filesystem", count: 1, href: "#"},
                        {label: "filter", count: 2, href: "#"},
                        {label: "flash", count: 4, href: "#"},
                        {label: "flexbox", count: 16, href: "#"},
                        {label: "flickity", count: 1, href: "#"},
                        {label: "forge", count: 44, href: "#"},
                        {label: "form", count: 32, href: "#"},
                        {label: "form request", count: 2, href: "#"},
                        {label: "fortrabbit", count: 5, href: "#"},
                        {label: "front-end", count: 86, href: "#"},
                        {label: "function", count: 1, href: "#"},
                        {label: "fundamental", count: 5, href: "#"},
                    ]
                },
                {
                    index: 'g',
                    items: [
                        {label: "generator", count: 2, href: "#"},
                        {label: "git", count: 13, href: "#"},
                        {label: "github", count: 27, href: "#"},
                        {label: "google", count: 2, href: "#"},
                        {label: "graph", count: 8, href: "#"},
                        {label: "gravatar", count: 4, href: "#"},
                        {label: "grid", count: 7, href: "#"},
                        {label: "guard", count: 1, href: "#"},
                        {label: "gulp", count: 8, href: "#"},
                        {label: "guzzle", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'h',
                    items: [
                        {label: "handlebars", count: 1, href: "#"},
                        {label: "handler", count: 1, href: "#"},
                        {label: "hash", count: 1, href: "#"},
                        {label: "header", count: 1, href: "#"},
                        {label: "homestead", count: 6, href: "#"},
                        {label: "hook", count: 1, href: "#"},
                        {label: "horizon", count: 1, href: "#"},
                        {label: "hover", count: 1, href: "#"},
                        {label: "html5", count: 5, href: "#"},
                    ]
                },
                {
                    index: 'i',
                    items: [
                        {label: "imaging", count: 1, href: "#"},
                        {label: "infinite scroll", count: 1, href: "#"},
                        {label: "inheritance", count: 1, href: "#"},
                        {label: "integration testing", count: 5, href: "#"},
                        {label: "integration-testing", count: 6, href: "#"},
                        {label: "interface", count: 9, href: "#"},
                        {label: "interview", count: 1, href: "#"},
                        {label: "ioc", count: 8, href: "#"},
                        {label: "iron", count: 2, href: "#"},
                        {label: "iterator", count: 1, href: "#"},
                    ]
                },
                {
                    index: 'j',
                    items: [
                        {label: "javascript", count: 107, href: "#"},
                        {label: "job", count: 4, href: "#"},
                    ]
                },
                {
                    index: 'k',
                    items: [
                        {label: "kahlan", count: 1, href: "#"},
                        {label: "kata", count: 6, href: "#"},
                    ]
                },
                {
                    index: 'l',
                    items: [
                        {label: "laravel", count: 119, href: "#"},
                        {label: "laravel mix", count: 4, href: "#"},
                        {label: "laravel-mix", count: 1, href: "#"},
                        {label: "lightbox", count: 1, href: "#"},
                        {label: "listener", count: 3, href: "#"},
                        {label: "log", count: 1, href: "#"},
                        {label: "logging", count: 1, href: "#"},
                    ]
                },
                {
                    index: 'm',
                    items: [
                        {label: "mac", count: 1, href: "#"},
                        {label: "macro", count: 1, href: "#"},
                        {label: "mail", count: 22, href: "#"},
                        {label: "mail postmark", count: 1, href: "#"},
                        {label: "mailable", count: 1, href: "#"},
                        {label: "mailcatcher", count: 2, href: "#"},
                        {label: "mailchimp", count: 2, href: "#"},
                        {label: "mamp", count: 1, href: "#"},
                        {label: "mandrill", count: 2, href: "#"},
                        {label: "markdown", count: 2, href: "#"},
                        {label: "mass assignment", count: 3, href: "#"},
                        {label: "memcached", count: 1, href: "#"},
                        {label: "memoize", count: 1, href: "#"},
                        {label: "menu", count: 2, href: "#"},
                        {label: "microservice", count: 1, href: "#"},
                        {label: "middleware", count: 9, href: "#"},
                        {label: "migration", count: 7, href: "#"},
                        {label: "mix", count: 17, href: "#"},
                        {label: "mixin", count: 1, href: "#"},
                        {label: "mobile", count: 2, href: "#"},
                        {label: "mocha", count: 1, href: "#"},
                        {label: "mock", count: 4, href: "#"},
                        {label: "mockery", count: 5, href: "#"},
                        {label: "modal", count: 9, href: "#"},
                        {label: "model", count: 3, href: "#"},
                        {label: "model change", count: 1, href: "#"},
                        {label: "mustache", count: 2, href: "#"},
                        {label: "mvc", count: 2, href: "#"},
                        {label: "mysql", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'n',
                    items: [
                        {label: "namespace", count: 3, href: "#"},
                        {label: "new relic", count: 1, href: "#"},
                        {label: "nginx", count: 1, href: "#"},
                        {label: "node", count: 5, href: "#"},
                        {label: "notification", count: 12, href: "#"},
                        {label: "nova", count: 15, href: "#"},
                        {label: "npm", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'o',
                    items: [
                        {label: "oauth", count: 2, href: "#"},
                        {label: "oh-unit", count: 1, href: "#"},
                        {label: "oop", count: 13, href: "#"},
                    ]
                },
                {
                    index: 'p',
                    items: [
                        {label: "package", count: 11, href: "#"},
                        {label: "packagist", count: 5, href: "#"},
                        {label: "pagination", count: 8, href: "#"},
                        {label: "partial", count: 1, href: "#"},
                        {label: "passport", count: 1, href: "#"},
                        {label: "password reset", count: 3, href: "#"},
                        {label: "pdo", count: 1, href: "#"},
                        {label: "performance", count: 11, href: "#"},
                        {label: "php", count: 66, href: "#"},
                        {label: "phpspec", count: 22, href: "#"},
                        {label: "phpstorm", count: 29, href: "#"},
                        {label: "phpunit", count: 66, href: "#"},
                        {label: "phpunit activity", count: 2, href: "#"},
                        {label: "pipeline", count: 2, href: "#"},
                        {label: "pivot", count: 2, href: "#"},
                        {label: "pjax", count: 1, href: "#"},
                        {label: "plugin", count: 1, href: "#"},
                        {label: "policy", count: 6, href: "#"},
                        {label: "polymorphism", count: 14, href: "#"},
                        {label: "portal", count: 2, href: "#"},
                        {label: "postcss", count: 1, href: "#"},
                        {label: "postgresql", count: 1, href: "#"},
                        {label: "presenter", count: 4, href: "#"},
                        {label: "preset", count: 5, href: "#"},
                        {label: "principle", count: 8, href: "#"},
                        {label: "profile", count: 2, href: "#"},
                        {label: "promise", count: 2, href: "#"},
                        {label: "prophecy", count: 1, href: "#"},
                        {label: "provider", count: 1, href: "#"},
                        {label: "psr", count: 3, href: "#"},
                        {label: "psr2", count: 1, href: "#"},
                        {label: "pusher", count: 11, href: "#"},
                    ]
                },
                {
                    index: 'q',
                    items: [
                        {label: "query builder", count: 1, href: "#"},
                        {label: "query object", count: 2, href: "#"},
                        {label: "query scope", count: 2, href: "#"},
                        {label: "queue", count: 17, href: "#"},
                    ]
                },
                {
                    index: 'r',
                    items: [
                        {label: "rate", count: 1, href: "#"},
                        {label: "rating", count: 2, href: "#"},
                        {label: "react", count: 1, href: "#"},
                        {label: "recaptcha", count: 1, href: "#"},
                        {label: "redis", count: 16, href: "#"},
                        {label: "refactor", count: 67, href: "#"},
                        {label: "refactoring", count: 4, href: "#"},
                        {label: "reflection", count: 2, href: "#"},
                        {label: "registration", count: 4, href: "#"},
                        {label: "regression testing", count: 3, href: "#"},
                        {label: "regular expression", count: 9, href: "#"},
                        {label: "relationship", count: 8, href: "#"},
                        {label: "render", count: 1, href: "#"},
                        {label: "report", count: 1, href: "#"},
                        {label: "reporting", count: 2, href: "#"},
                        {label: "repository", count: 9, href: "#"},
                        {label: "request", count: 1, href: "#"},
                        {label: "resource", count: 4, href: "#"},
                        {label: "responsive design", count: 1, href: "#"},
                        {label: "rest", count: 8, href: "#"},
                        {label: "revert", count: 1, href: "#"},
                        {label: "route", count: 11, href: "#"},
                        {label: "routing", count: 8, href: "#"},
                        {label: "rss", count: 1, href: "#"},
                    ]
                },
                {
                    index: 's',
                    items: [
                        {label: "s3", count: 2, href: "#"},
                        {label: "sanitize", count: 2, href: "#"},
                        {label: "sass", count: 7, href: "#"},
                        {label: "schema", count: 1, href: "#"},
                        {label: "scope", count: 2, href: "#"},
                        {label: "scout", count: 3, href: "#"},
                        {label: "scroll", count: 1, href: "#"},
                        {label: "search", count: 12, href: "#"},
                        {label: "security", count: 24, href: "#"},
                        {label: "seed", count: 8, href: "#"},
                        {label: "selenium", count: 2, href: "#"},
                        {label: "sequel pro", count: 1, href: "#"},
                        {label: "server", count: 53, href: "#"},
                        {label: "service", count: 1, href: "#"},
                        {label: "service container", count: 3, href: "#"},
                        {label: "service provider", count: 6, href: "#"},
                        {label: "session", count: 5, href: "#"},
                        {label: "setting", count: 2, href: "#"},
                        {label: "singleton", count: 1, href: "#"},
                        {label: "slack", count: 2, href: "#"},
                        {label: "slot", count: 1, href: "#"},
                        {label: "slug", count: 3, href: "#"},
                        {label: "snippet", count: 2, href: "#"},
                        {label: "socket.io", count: 2, href: "#"},
                        {label: "solid", count: 8, href: "#"},
                        {label: "sort", count: 1, href: "#"},
                        {label: "sorting", count: 1, href: "#"},
                        {label: "spa", count: 6, href: "#"},
                        {label: "spam", count: 3, href: "#"},
                        {label: "spark", count: 7, href: "#"},
                        {label: "spy", count: 1, href: "#"},
                        {label: "sql", count: 1, href: "#"},
                        {label: "sqlite", count: 3, href: "#"},
                        {label: "ssh", count: 2, href: "#"},
                        {label: "ssl", count: 2, href: "#"},
                        {label: "staging", count: 2, href: "#"},
                        {label: "star", count: 2, href: "#"},
                        {label: "state", count: 2, href: "#"},
                        {label: "status codes", count: 1, href: "#"},
                        {label: "storage", count: 1, href: "#"},
                        {label: "strategy", count: 3, href: "#"},
                        {label: "stripe", count: 24, href: "#"},
                        {label: "structure", count: 2, href: "#"},
                        {label: "styleci", count: 1, href: "#"},
                        {label: "stylus", count: 1, href: "#"},
                        {label: "sublime text", count: 14, href: "#"},
                        {label: "subscription", count: 1, href: "#"},
                        {label: "supervisor", count: 1, href: "#"},
                        {label: "symfony", count: 10, href: "#"},
                        {label: "sync", count: 1, href: "#"},
                    ]
                },
                {
                    index: 't',
                    items: [
                        {label: "tag", count: 2, href: "#"},
                        {label: "tailwind", count: 17, href: "#"},
                        {label: "taylor", count: 3, href: "#"},
                        {label: "taylor-made", count: 10, href: "#"},
                        {label: "td", count: 1, href: "#"},
                        {label: "tdd", count: 73, href: "#"},
                        {label: "telescope", count: 1, href: "#"},
                        {label: "template", count: 3, href: "#"},
                        {label: "term", count: 1, href: "#"},
                        {label: "terminal", count: 4, href: "#"},
                        {label: "test", count: 1, href: "#"},
                        {label: "testdummy", count: 4, href: "#"},
                        {label: "testimonial", count: 1, href: "#"},
                        {label: "testing", count: 195, href: "#"},
                        {label: "theme", count: 3, href: "#"},
                        {label: "throttle", count: 2, href: "#"},
                        {label: "thumbnail", count: 1, href: "#"},
                        {label: "timer", count: 2, href: "#"},
                        {label: "tip", count: 1, href: "#"},
                        {label: "token", count: 3, href: "#"},
                        {label: "tool", count: 1, href: "#"},
                        {label: "tooltip", count: 1, href: "#"},
                        {label: "touch", count: 1, href: "#"},
                        {label: "trait", count: 4, href: "#"},
                        {label: "transition", count: 1, href: "#"},
                        {label: "travis", count: 2, href: "#"},
                        {label: "trix", count: 2, href: "#"},
                        {label: "turbolinks", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'o',
                    items: [
                        {label: "oauth", count: 2, href: "#"},
                        {label: "oh-unit", count: 1, href: "#"},
                        {label: "oop", count: 13, href: "#"},
                    ]
                },
                {
                    index: 'p',
                    items: [
                        {label: "package", count: 11, href: "#"},
                        {label: "packagist", count: 5, href: "#"},
                        {label: "pagination", count: 8, href: "#"},
                        {label: "partial", count: 1, href: "#"},
                        {label: "passport", count: 1, href: "#"},
                        {label: "password reset", count: 3, href: "#"},
                        {label: "pdo", count: 1, href: "#"},
                        {label: "performance", count: 11, href: "#"},
                        {label: "php", count: 66, href: "#"},
                        {label: "phpspec", count: 22, href: "#"},
                        {label: "phpstorm", count: 29, href: "#"},
                        {label: "phpunit", count: 66, href: "#"},
                        {label: "phpunit activity", count: 2, href: "#"},
                        {label: "pipeline", count: 2, href: "#"},
                        {label: "pivot", count: 2, href: "#"},
                        {label: "pjax", count: 1, href: "#"},
                        {label: "plugin", count: 1, href: "#"},
                        {label: "policy", count: 6, href: "#"},
                        {label: "polymorphism", count: 14, href: "#"},
                        {label: "portal", count: 2, href: "#"},
                        {label: "postcss", count: 1, href: "#"},
                        {label: "postgresql", count: 1, href: "#"},
                        {label: "presenter", count: 4, href: "#"},
                        {label: "preset", count: 5, href: "#"},
                        {label: "principle", count: 8, href: "#"},
                        {label: "profile", count: 2, href: "#"},
                        {label: "promise", count: 2, href: "#"},
                        {label: "prophecy", count: 1, href: "#"},
                        {label: "provider", count: 1, href: "#"},
                        {label: "psr", count: 3, href: "#"},
                        {label: "psr2", count: 1, href: "#"},
                        {label: "pusher", count: 11, href: "#"},
                    ]
                },
                {
                    index: 'q',
                    items: [
                        {label: "query builder", count: 1, href: "#"},
                        {label: "query object", count: 2, href: "#"},
                        {label: "query scope", count: 2, href: "#"},
                        {label: "queue", count: 17, href: "#"},
                    ]
                },
                {
                    index: 'r',
                    items: [
                        {label: "rate", count: 1, href: "#"},
                        {label: "rating", count: 2, href: "#"},
                        {label: "react", count: 1, href: "#"},
                        {label: "recaptcha", count: 1, href: "#"},
                        {label: "redis", count: 16, href: "#"},
                        {label: "refactor", count: 67, href: "#"},
                        {label: "refactoring", count: 4, href: "#"},
                        {label: "reflection", count: 2, href: "#"},
                        {label: "registration", count: 4, href: "#"},
                        {label: "regression testing", count: 3, href: "#"},
                        {label: "regular expression", count: 9, href: "#"},
                        {label: "relationship", count: 8, href: "#"},
                        {label: "render", count: 1, href: "#"},
                        {label: "report", count: 1, href: "#"},
                        {label: "reporting", count: 2, href: "#"},
                        {label: "repository", count: 9, href: "#"},
                        {label: "request", count: 1, href: "#"},
                        {label: "resource", count: 4, href: "#"},
                        {label: "responsive design", count: 1, href: "#"},
                        {label: "rest", count: 8, href: "#"},
                        {label: "revert", count: 1, href: "#"},
                        {label: "route", count: 11, href: "#"},
                        {label: "routing", count: 8, href: "#"},
                        {label: "rss", count: 1, href: "#"},
                    ]
                },
                {
                    index: 's',
                    items: [
                        {label: "s3", count: 2, href: "#"},
                        {label: "sanitize", count: 2, href: "#"},
                        {label: "sass", count: 7, href: "#"},
                        {label: "schema", count: 1, href: "#"},
                        {label: "scope", count: 2, href: "#"},
                        {label: "scout", count: 3, href: "#"},
                        {label: "scroll", count: 1, href: "#"},
                        {label: "search", count: 12, href: "#"},
                        {label: "security", count: 24, href: "#"},
                        {label: "seed", count: 8, href: "#"},
                        {label: "selenium", count: 2, href: "#"},
                        {label: "sequel pro", count: 1, href: "#"},
                        {label: "server", count: 53, href: "#"},
                        {label: "service", count: 1, href: "#"},
                        {label: "service container", count: 3, href: "#"},
                        {label: "service provider", count: 6, href: "#"},
                        {label: "session", count: 5, href: "#"},
                        {label: "setting", count: 2, href: "#"},
                        {label: "singleton", count: 1, href: "#"},
                        {label: "slack", count: 2, href: "#"},
                        {label: "slot", count: 1, href: "#"},
                        {label: "slug", count: 3, href: "#"},
                        {label: "snippet", count: 2, href: "#"},
                        {label: "socket.io", count: 2, href: "#"},
                        {label: "solid", count: 8, href: "#"},
                        {label: "sort", count: 1, href: "#"},
                        {label: "sorting", count: 1, href: "#"},
                        {label: "spa", count: 6, href: "#"},
                        {label: "spam", count: 3, href: "#"},
                        {label: "spark", count: 7, href: "#"},
                        {label: "spy", count: 1, href: "#"},
                        {label: "sql", count: 1, href: "#"},
                        {label: "sqlite", count: 3, href: "#"},
                        {label: "ssh", count: 2, href: "#"},
                        {label: "ssl", count: 2, href: "#"},
                        {label: "staging", count: 2, href: "#"},
                        {label: "star", count: 2, href: "#"},
                        {label: "state", count: 2, href: "#"},
                        {label: "status codes", count: 1, href: "#"},
                        {label: "storage", count: 1, href: "#"},
                        {label: "strategy", count: 3, href: "#"},
                        {label: "stripe", count: 24, href: "#"},
                        {label: "structure", count: 2, href: "#"},
                        {label: "styleci", count: 1, href: "#"},
                        {label: "stylus", count: 1, href: "#"},
                        {label: "sublime text", count: 14, href: "#"},
                        {label: "subscription", count: 1, href: "#"},
                        {label: "supervisor", count: 1, href: "#"},
                        {label: "symfony", count: 10, href: "#"},
                        {label: "sync", count: 1, href: "#"},
                    ]
                },
                {
                    index: 't',
                    items: [
                        {label: "tag", count: 2, href: "#"},
                        {label: "tailwind", count: 17, href: "#"},
                        {label: "taylor", count: 3, href: "#"},
                        {label: "taylor-made", count: 10, href: "#"},
                        {label: "td", count: 1, href: "#"},
                        {label: "tdd", count: 73, href: "#"},
                        {label: "telescope", count: 1, href: "#"},
                        {label: "template", count: 3, href: "#"},
                        {label: "term", count: 1, href: "#"},
                        {label: "terminal", count: 4, href: "#"},
                        {label: "test", count: 1, href: "#"},
                        {label: "testdummy", count: 4, href: "#"},
                        {label: "testimonial", count: 1, href: "#"},
                        {label: "testing", count: 195, href: "#"},
                        {label: "theme", count: 3, href: "#"},
                        {label: "throttle", count: 2, href: "#"},
                        {label: "thumbnail", count: 1, href: "#"},
                        {label: "timer", count: 2, href: "#"},
                        {label: "tip", count: 1, href: "#"},
                        {label: "token", count: 3, href: "#"},
                        {label: "tool", count: 1, href: "#"},
                        {label: "tooltip", count: 1, href: "#"},
                        {label: "touch", count: 1, href: "#"},
                        {label: "trait", count: 4, href: "#"},
                        {label: "transition", count: 1, href: "#"},
                        {label: "travis", count: 2, href: "#"},
                        {label: "trix", count: 2, href: "#"},
                        {label: "turbolinks", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'u',
                    items: [
                        {label: "unit testing", count: 1, href: "#"},
                        {label: "upload", count: 4, href: "#"},
                    ]
                },
                {
                    index: 'v',
                    items: [
                        {label: "vagrant", count: 11, href: "#"},
                        {label: "valet", count: 3, href: "#"},
                        {label: "validation", count: 25, href: "#"},
                        {label: "value object", count: 3, href: "#"},
                        {label: "video", count: 5, href: "#"},
                        {label: "view", count: 9, href: "#"},
                        {label: "viewport", count: 1, href: "#"},
                        {label: "vim", count: 25, href: "#"},
                        {label: "virtual file system", count: 1, href: "#"},
                        {label: "virtual machine", count: 8, href: "#"},
                        {label: "vue", count: 141, href: "#"},
                        {label: "vue-router", count: 1, href: "#"},
                        {label: "vuex", count: 3, href: "#"},
                    ]
                },
                {
                    index: 'w',
                    items: [
                        {label: "webpack", count: 32, href: "#"},
                        {label: "workbench", count: 1, href: "#"},
                        {label: "worker", count: 10, href: "#"},
                        {label: "workflow", count: 25, href: "#"},
                        {label: "wysiwyg", count: 2, href: "#"},
                    ]
                },
                {
                    index: 'x',
                    items: [
                        {label: "xdebug", count: 2, href: "#"},
                    ]
                },
            ]
        }
    }
}
</script>
